name: test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review, edited, closed]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo ${{ secrets.TEST }} | base64 
